FROM node:18.10-alpine3.15 AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN rm -rf ./dist && npm run generate

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
